package com.reelsomet.poster.automation

enum class InsightsState {
    IDLE,
    OPENING_INSTAGRAM,
    WAITING_FOR_INSTAGRAM,
    NAVIGATING_TO_PROFILE,
    WAITING_FOR_PROFILE,
    REFRESHING_PROFILE,
    CHECKING_ACCOUNT,
    OPENING_ACCOUNT_SWITCHER,
    SWITCHING_ACCOUNT,
    WAITING_ACCOUNT_SWITCH,
    TAPPING_REELS_TAB,
    WAITING_REELS_GRID,
    TAPPING_REEL,
    WAITING_REEL_OPEN,
    SKIPPING_REELS,
    READING_REEL_CAPTION,
    TAPPING_VIEW_INSIGHTS,
    WAITING_INSIGHTS_SCREEN,
    READING_METRICS,
    PRESSING_BACK_FROM_INSIGHTS,
    SWIPING_TO_NEXT_REEL,
    ADVANCING_TO_NEXT_ACCOUNT,
    COMPLETED,
    FAILED;

    fun isActive(): Boolean = this != IDLE && this != COMPLETED && this != FAILED
}
