package com.reelsomet.poster.automation

enum class PostingState {
    IDLE,
    OPENING_INSTAGRAM,
    WAITING_FOR_INSTAGRAM,
    REFRESHING_PROFILE,
    CHECKING_ACCOUNT,
    OPENING_ACCOUNT_SWITCHER,
    SWITCHING_ACCOUNT,
    WAITING_ACCOUNT_SWITCH,
    TAPPING_PROFILE_REELS_TAB,
    WAITING_PROFILE_REELS_GRID,
    OPENING_PROFILE_REEL,
    WAITING_TRIAL_REEL_ENTRYPOINT,
    WAITING_CREATE_TRIAL_REEL,
    TAPPING_CREATE,
    WAITING_CREATE_MENU,
    SELECTING_CREATE_REEL,
    WAITING_FOR_GALLERY,
    SELECTING_VIDEO,
    WAITING_VIDEO_LOAD,
    TAPPING_NEXT_AFTER_VIDEO,
    WAITING_EDIT_SCREEN,
    TAPPING_NEXT_AFTER_EDIT,
    WAITING_SHARE_SCREEN,
    ENTERING_CAPTION,
    TAPPING_SHARE,
    WAITING_FOR_UPLOAD,
    VERIFYING_SUCCESS,
    COMPLETED,
    FAILED;

    fun isActive(): Boolean = this != IDLE && this != COMPLETED && this != FAILED
}
